###
GET http://localhost:8000/api/crops

###
GET http://localhost:8000/api/crops/spring

### delete a crop
DELETE http://localhost:8000/api/crops/61

### create a crop
POST http://localhost:8000/api/crops/
Content-Type: application/json

{
    "name": "Sugarcane",
    "growth_time": 5,
    "regrowth_time": 1,
    "seed_price": 50,
    "sell_price": 20,
    "season": "spring"
}

### update a crop
PUT http://localhost:8000/api/crops/63
Content-Type: application/json

{
    "name": "Sugarcane",
    "growth_time": 5,
    "regrowth_time": 1,
    "seed_price": 50,
    "sell_price": 25,
    "season": "spring"
}

