DELETE FROM crop;

INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Sugarcane', 5, true, 1, 50, 20, 'Spring');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Strawberry', 10, true, 4, 145, 90, 'Spring');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Cauliflower', 10, false, 0, 70, 155, 'Spring');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Chard', 6, false, 0, 50, 100, 'Spring');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Potato', 5, false, 0, 25, 66, 'Spring');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Radish', 6, false, 0, 60, 108, 'Spring');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Cucumber', 9, true, 3, 25, 34, 'Spring');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Pea', 11, true, 4, 45, 50, 'Spring');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Poppy', 7, false, 0, 30, 72, 'Spring');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Snowdrop', 12, false, 0, 45, 110, 'Spring');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Carrott', 7, false, 0, 35, 70, 'Spring');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Daisy', 4, false, 0, 15, 35, 'Spring');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Turnip', 4, false, 0, 15, 35, 'Spring');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Lettuce', 5, false, 0, 20, 42, 'Spring');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Peony', 4, false, 0, 20, 42, 'Spring');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Watermelon', 11, false, 0, 50, 95, 'Spring');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Soybean', 7, true, 4, 20, 15, 'Spring');

INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Pineapple', 9, false, 0, 110, 185, 'Summer');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Radish', 6, false, 0, 60, 108, 'Summer');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Lily', 9, false, 0, 60, 132, 'Summer');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Melon', 12, false, 0, 130, 215, 'Summer');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Hot Pepper', 7, true, 3, 40, 30, 'Summer');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Bell Pepper', 8, true, 4, 70, 40, 'Summer');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Iris', 10, false, 0, 30, 88, 'Summer');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Red Cabbage', 9, false, 0, 45, 95, 'Summer');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Okra', 9, true, 6, 60, 50, 'Summer');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Sunflower', 8, false, 0, 20, 60, 'Summer');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Cotton', 9, false, 0, 50, 95, 'Summer');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Blackberry', 11, true, 4, 40, 35, 'Summer');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Coffee Bean', 11, true, 2, 70, 22, 'Summer');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Blueberry', 10, true, 4, 50, 35, 'Summer');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Rose', 6, false, 0, 20, 45, 'Summer');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Tomato', 10, true, 4, 25, 28, 'Summer');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Gardenia', 5, false, 0, 20, 40, 'Summer');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Starfruit', 13, false, 0, 60, 100, 'Summer');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Wheat', 5, false, 0, 15, 30, 'Summer');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Corn', 12, true, 4, 25, 20, 'Summer');

INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Lily', 9, false, 0, 60, 132, 'Fall');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Cactus', 13, false, 0, 300, 400, 'Fall');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Pumpkin', 13, true, 7, 90, 100, 'Fall');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Garlic', 9, false, 0, 30, 95, 'Fall');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Hot Pepper', 7, true, 3, 40, 30, 'Fall');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Taro Root', 5, false, 0, 35, 70, 'Fall');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Bak Choy', 8, true, 5, 60, 50, 'Fall');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Eggplant', 9, true, 3, 35, 30, 'Fall');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Blue Dahlia', 4, false, 0, 50, 75, 'Fall');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Cranberry', 5, true, 2, 20, 15, 'Fall');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Orchid', 8, false, 0, 75, 120, 'Fall');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Grape', 9, true, 6, 150, 65, 'Fall');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Fairy Rose', 8, false, 0, 135, 166, 'Fall');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Artichoke', 8, true, 4, 45, 25, 'Fall');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Basil', 5, false, 0, 20, 35, 'Fall');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Rice', 9, false, 0, 15, 40, 'Fall');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Amaranth', 8, true, 5, 25, 20, 'Fall');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Sweet Potato', 9, true, 4, 60, 25, 'Fall');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Beet', 6, true, 4, 20, 15, 'Fall');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Barley', 8, false, 0, 100, 116, 'Fall');

INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Snowdrop', 12, false, 0, 45, 110, 'Winter');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Cotton', 9, false, 0, 50, 95, 'Winter');
INSERT INTO crop (name, growth_time, regrowth, regrowth_time, seed_price, sell_price, season) VALUES ('Tea Leaf', 11, false, 0, 25, 60, 'Winter');